// Per-country bonus-world theme + vocab. The runner component reads this
// to skin its scene and supply the translation-match pairs.
//
// Vocab is curated to match the learning content for each country's
// section(s). English keys are the prompt the player sees; Spanish values
// are the items they must catch.

export type CountryTheme = {
  // Country-specific name shown on the World button + on the runner's
  // welcome banner (e.g., Mexico → "Frida's Casa Azul").
  worldName: string
  // Optional looping landmark video shown behind the gameplay layer.
  // Free / no-copyright stock URLs. When set, the runner replaces the
  // sky/mountain layers with the video and overlays a subtle dim so
  // gameplay stays readable.
  videoBg?: string
  // Background — vertical sky gradient (top → bottom)
  sky: [string, string, string, string]
  // Distant mountain silhouette
  mountain: [string, string]
  // Ground stripe + base color
  ground: { stripeA: string; stripeB: string; base: string; topBorder: string }
  // Foreground decor emojis sliding by
  decor: [string, string, string, string]
  // Pill color for the Spanish vocab items
  itemColor: string
  // Highlight color used in the "CATCH <english>" banner
  bannerHighlight: string
  // English title shown on the win/lose card
  loseHint: string
  // Translation pairs (English → Spanish) sourced from the country's songs
  vocab: { en: string; es: string }[]
}

const baseGround = {
  stripeA: "#B45309",
  stripeB: "#A0480A",
  base: "#7C3A09",
  topBorder: "#5C2A06",
}

export const COUNTRY_THEMES: Record<string, CountryTheme> = {
  // ── Noun Galaxy ──────────────────────────────────────────────
  "Mexico": {
    worldName: "Casa Azul",
    sky: ["#FFE5B4", "#FDD89A", "#F4A460", "#D4663D"],
    mountain: ["#8B5A3C", "#6B4423"],
    ground: baseGround,
    decor: ["🌵", "🎺", "🌶️", "🪅"],
    itemColor: "#0A75D3",
    bannerHighlight: "#FFE066",
    loseHint: "Try again to reach the carrot.",
    vocab: [
      { es: "perro",      en: "dog" },
      { es: "niño",       en: "child" },
      { es: "lluvia",     en: "rain" },
      { es: "carro",      en: "car" },
      { es: "llama",      en: "flame" },
      { es: "churro",     en: "donut" },
      { es: "vamos",      en: "let's go" },
      { es: "canta",      en: "sing" },
      { es: "vocales",    en: "vowels" },
      { es: "abecedario", en: "alphabet" },
      { es: "ya",         en: "now" },
    ],
  },
  "Guatemala": {
    worldName: "Tikal",
    sky: ["#A7F3D0", "#86EFAC", "#22C55E", "#15803D"],
    mountain: ["#1F4D1F", "#0E3010"],
    ground: { stripeA: "#3F6B3A", stripeB: "#2E5430", base: "#1F3D24", topBorder: "#0E2410" },
    decor: ["🌋", "🦜", "🌸", "🧶"],
    itemColor: "#15803D",
    bannerHighlight: "#FBCFE8",
    loseHint: "Stretch and try again!",
    vocab: [
      { es: "cabeza",  en: "head" },
      { es: "manos",   en: "hands" },
      { es: "ojos",    en: "eyes" },
      { es: "pies",    en: "feet" },
      { es: "brazos",  en: "arms" },
      { es: "boca",    en: "mouth" },
      { es: "nariz",   en: "nose" },
      { es: "oreja",   en: "ear" },
      { es: "pelo",    en: "hair" },
      { es: "cuerpo",  en: "body" },
      { es: "rodilla", en: "knee" },
      { es: "espalda", en: "back" },
    ],
  },
  "El Salvador": {
    worldName: "Santa Ana Volcano",
    sky: ["#FFE4B5", "#FFB347", "#FF6347", "#B91C1C"],
    mountain: ["#7C2D12", "#451A03"],
    ground: { stripeA: "#7C2D12", stripeB: "#5C1F0A", base: "#3E1306", topBorder: "#1F0903" },
    decor: ["🌽", "🌺", "🌊", "🥟"],
    itemColor: "#B91C1C",
    bannerHighlight: "#FDE68A",
    loseHint: "¡Otra vez! Try again.",
    vocab: [
      { es: "ropa",      en: "clothes" },
      { es: "camisa",    en: "shirt" },
      { es: "zapatos",   en: "shoes" },
      { es: "gorra",     en: "cap" },
      { es: "falda",     en: "skirt" },
      { es: "vestido",   en: "dress" },
      { es: "botas",     en: "boots" },
      { es: "guantes",   en: "gloves" },
      { es: "pantalón",  en: "pants" },
      { es: "suéter",    en: "sweater" },
    ],
  },
  "Honduras": {
    worldName: "Copán Ruinas",
    sky: ["#A7F3D0", "#5EEAD4", "#06B6D4", "#0E7490"],
    mountain: ["#0F766E", "#134E4A"],
    ground: { stripeA: "#365314", stripeB: "#1E3008", base: "#142105", topBorder: "#0A1003" },
    decor: ["🌴", "🐢", "🐠", "🏝️"],
    itemColor: "#0E7490",
    bannerHighlight: "#FDE68A",
    loseHint: "Vamos otra vez.",
    vocab: [
      { es: "familia",  en: "family" },
      { es: "papá",     en: "dad" },
      { es: "mamá",     en: "mom" },
      { es: "hermano",  en: "brother" },
      { es: "hermana",  en: "sister" },
      { es: "abuela",   en: "grandma" },
      { es: "abuelo",   en: "grandpa" },
      { es: "mascota",  en: "pet" },
      { es: "gato",     en: "cat" },
      { es: "perro",    en: "dog" },
      { es: "tío",      en: "uncle" },
      { es: "tía",      en: "aunt" },
    ],
  },
  "Nicaragua": {
    worldName: "Granada",
    sky: ["#FED7AA", "#FB923C", "#EA580C", "#9A3412"],
    mountain: ["#7C2D12", "#3E1306"],
    ground: { stripeA: "#52525B", stripeB: "#3F3F46", base: "#27272A", topBorder: "#18181B" },
    decor: ["🌋", "🚣", "🦋", "🥁"],
    itemColor: "#EA580C",
    bannerHighlight: "#FEF3C7",
    loseHint: "Try again!",
    vocab: [
      { es: "viaje",     en: "trip" },
      { es: "playa",     en: "beach" },
      { es: "lago",      en: "lake" },
      { es: "volcán",    en: "volcano" },
      { es: "barco",     en: "boat" },
      { es: "avión",     en: "plane" },
      { es: "bus",       en: "bus" },
      { es: "tren",      en: "train" },
      { es: "ciudad",    en: "city" },
      { es: "pueblo",    en: "town" },
    ],
  },
  "Costa Rica": {
    worldName: "Monteverde Cloud Forest",
    sky: ["#BBF7D0", "#86EFAC", "#22C55E", "#166534"],
    mountain: ["#14532D", "#052E16"],
    ground: { stripeA: "#3F6B3A", stripeB: "#2E5430", base: "#1F3D24", topBorder: "#0E2410" },
    decor: ["🦥", "🐸", "🌺", "🦜"],
    itemColor: "#166534",
    bannerHighlight: "#FEF3C7",
    loseHint: "¡Pura vida! Otra vez.",
    vocab: [
      { es: "uno",   en: "one" },
      { es: "dos",   en: "two" },
      { es: "tres",  en: "three" },
      { es: "cuatro",en: "four" },
      { es: "cinco", en: "five" },
      { es: "seis",  en: "six" },
      { es: "siete", en: "seven" },
      { es: "ocho",  en: "eight" },
      { es: "nueve", en: "nine" },
      { es: "diez",  en: "ten" },
    ],
  },
  "Panama": {
    worldName: "Panama Canal",
    sky: ["#DBEAFE", "#93C5FD", "#3B82F6", "#1D4ED8"],
    mountain: ["#1E3A8A", "#172554"],
    ground: { stripeA: "#0E7490", stripeB: "#155E75", base: "#0E4257", topBorder: "#0C2233" },
    decor: ["🚢", "🌴", "🎩", "🌅"],
    itemColor: "#1D4ED8",
    bannerHighlight: "#FDE68A",
    loseHint: "Try again.",
    vocab: [
      { es: "hoy",       en: "today" },
      { es: "mañana",    en: "tomorrow" },
      { es: "ayer",      en: "yesterday" },
      { es: "ahora",     en: "now" },
      { es: "después",   en: "later" },
      { es: "antes",     en: "before" },
      { es: "siempre",   en: "always" },
      { es: "nunca",     en: "never" },
      { es: "lunes",     en: "Monday" },
      { es: "viernes",   en: "Friday" },
    ],
  },
  "Puerto Rico": {
    worldName: "Flamenco Beach",
    sky: ["#FEF3C7", "#FDE68A", "#FBBF24", "#D97706"],
    mountain: ["#7C2D12", "#451A03"],
    ground: { stripeA: "#A16207", stripeB: "#854D0E", base: "#713F12", topBorder: "#3F2008" },
    decor: ["🏖️", "🐚", "🌴", "🥥"],
    itemColor: "#D97706",
    bannerHighlight: "#FBCFE8",
    loseHint: "¡Otra vez!",
    vocab: [
      { es: "feliz",     en: "happy" },
      { es: "triste",    en: "sad" },
      { es: "enojado",   en: "angry" },
      { es: "cansado",   en: "tired" },
      { es: "rojo",      en: "red" },
      { es: "azul",      en: "blue" },
      { es: "verde",     en: "green" },
      { es: "amarillo",  en: "yellow" },
      { es: "blanco",    en: "white" },
      { es: "negro",     en: "black" },
    ],
  },
  "Dominican Republic": {
    worldName: "Punta Cana",
    sky: ["#A7F3D0", "#FDE68A", "#FB923C", "#DC2626"],
    mountain: ["#7C2D12", "#451A03"],
    ground: { stripeA: "#0F766E", stripeB: "#115E59", base: "#134E4A", topBorder: "#042F2E" },
    decor: ["🥭", "🍹", "🪕", "🌴"],
    itemColor: "#DC2626",
    bannerHighlight: "#FEF3C7",
    loseHint: "¡Vamos! Try again.",
    vocab: [
      { es: "comida",    en: "food" },
      { es: "agua",      en: "water" },
      { es: "leche",     en: "milk" },
      { es: "pan",       en: "bread" },
      { es: "manzana",   en: "apple" },
      { es: "queso",     en: "cheese" },
      { es: "huevo",     en: "egg" },
      { es: "arroz",     en: "rice" },
      { es: "fruta",     en: "fruit" },
      { es: "carne",     en: "meat" },
    ],
  },
  "Cuba": {
    worldName: "Old Havana",
    sky: ["#FEF3C7", "#FDBA74", "#F97316", "#9A3412"],
    mountain: ["#7C2D12", "#451A03"],
    ground: { stripeA: "#92400E", stripeB: "#78350F", base: "#451A03", topBorder: "#1C0701" },
    decor: ["🎺", "🚗", "🚬", "🌴"],
    itemColor: "#B91C1C",
    bannerHighlight: "#FEF3C7",
    loseHint: "Otra vez, mi amigo.",
    vocab: [
      { es: "música",    en: "music" },
      { es: "baile",     en: "dance" },
      { es: "fiesta",    en: "party" },
      { es: "amigo",     en: "friend" },
      { es: "calle",     en: "street" },
      { es: "casa",      en: "house" },
      { es: "playa",     en: "beach" },
      { es: "sol",       en: "sun" },
      { es: "noche",     en: "night" },
      { es: "día",       en: "day" },
    ],
  },
  // ── Verb Galaxy ──────────────────────────────────────────────
  "Colombia": {
    worldName: "Cartagena Old Town",
    sky: ["#FCD34D", "#3B82F6", "#1E40AF", "#1E3A8A"],
    mountain: ["#1E3A8A", "#172554"],
    ground: { stripeA: "#166534", stripeB: "#14532D", base: "#052E16", topBorder: "#01160A" },
    decor: ["☕", "🌹", "🦋", "🥁"],
    itemColor: "#1D4ED8",
    bannerHighlight: "#FDE68A",
    loseHint: "Inténtalo otra vez.",
    vocab: [
      { es: "hablar",    en: "to talk" },
      { es: "cantar",    en: "to sing" },
      { es: "bailar",    en: "to dance" },
      { es: "caminar",   en: "to walk" },
      { es: "jugar",     en: "to play" },
      { es: "estudiar",  en: "to study" },
      { es: "trabajar",  en: "to work" },
      { es: "tomar",     en: "to take" },
      { es: "mirar",     en: "to look" },
      { es: "escuchar",  en: "to listen" },
    ],
  },
  "Venezuela": {
    worldName: "Angel Falls",
    sky: ["#FEF9C3", "#FDE047", "#A3E635", "#15803D"],
    mountain: ["#15803D", "#052E16"],
    ground: { stripeA: "#365314", stripeB: "#1E3008", base: "#142105", topBorder: "#0A1003" },
    decor: ["🏔️", "💧", "🦋", "🪕"],
    itemColor: "#15803D",
    bannerHighlight: "#FDE68A",
    loseHint: "¡Ánimo! Try again.",
    vocab: [
      { es: "comer",     en: "to eat" },
      { es: "beber",     en: "to drink" },
      { es: "leer",      en: "to read" },
      { es: "correr",    en: "to run" },
      { es: "ver",       en: "to see" },
      { es: "vender",    en: "to sell" },
      { es: "aprender",  en: "to learn" },
      { es: "tener",     en: "to have" },
      { es: "saber",     en: "to know" },
      { es: "querer",    en: "to want" },
    ],
  },
  "Ecuador": {
    worldName: "Galápagos Islands",
    sky: ["#DBEAFE", "#FEF3C7", "#FBBF24", "#92400E"],
    mountain: ["#1E3A8A", "#172554"],
    ground: { stripeA: "#7C2D12", stripeB: "#5C1F0A", base: "#451A03", topBorder: "#1C0701" },
    decor: ["🦎", "🌋", "🐢", "🌺"],
    itemColor: "#1E3A8A",
    bannerHighlight: "#FDE68A",
    loseHint: "¡Otra vez!",
    vocab: [
      { es: "ir",        en: "to go" },
      { es: "venir",     en: "to come" },
      { es: "vivir",     en: "to live" },
      { es: "salir",     en: "to leave" },
      { es: "subir",     en: "to go up" },
      { es: "abrir",     en: "to open" },
      { es: "escribir",  en: "to write" },
      { es: "decir",     en: "to say" },
      { es: "dormir",    en: "to sleep" },
      { es: "pedir",     en: "to ask for" },
    ],
  },
  "Peru": {
    worldName: "Machu Picchu",
    sky: ["#E0E7FF", "#A5B4FC", "#7C3AED", "#4C1D95"],
    mountain: ["#3F3F46", "#18181B"],
    ground: { stripeA: "#A16207", stripeB: "#713F12", base: "#451A03", topBorder: "#1C0701" },
    decor: ["🦙", "⛰️", "🪈", "🌽"],
    itemColor: "#4C1D95",
    bannerHighlight: "#FDE68A",
    loseHint: "Inténtalo otra vez.",
    vocab: [
      { es: "comí",      en: "I ate" },
      { es: "fui",       en: "I went" },
      { es: "hablé",     en: "I talked" },
      { es: "vi",        en: "I saw" },
      { es: "hice",      en: "I did" },
      { es: "tuve",      en: "I had" },
      { es: "vine",      en: "I came" },
      { es: "dije",      en: "I said" },
      { es: "leí",       en: "I read" },
      { es: "salí",      en: "I left" },
    ],
  },
  "Bolivia": {
    worldName: "Salar de Uyuni",
    sky: ["#FEF3C7", "#FDE68A", "#A78BFA", "#5B21B6"],
    mountain: ["#3730A3", "#1E1B4B"],
    ground: { stripeA: "#FAFAFA", stripeB: "#E4E4E7", base: "#A1A1AA", topBorder: "#52525B" },
    decor: ["🦙", "🧂", "🏔️", "🪕"],
    itemColor: "#5B21B6",
    bannerHighlight: "#FEF3C7",
    loseHint: "¡Otra vez!",
    vocab: [
      { es: "vivía",     en: "I used to live" },
      { es: "iba",       en: "I used to go" },
      { es: "tenía",     en: "I had (used to)" },
      { es: "era",       en: "I was" },
      { es: "estaba",    en: "I was (state)" },
      { es: "comía",     en: "I used to eat" },
      { es: "hablaba",   en: "I used to talk" },
      { es: "veía",      en: "I used to see" },
      { es: "hacía",     en: "I used to do" },
      { es: "leía",      en: "I used to read" },
    ],
  },
  "Paraguay": {
    worldName: "Cataratas del Monday",  // Paraguay (not provided by user; kept default)
    sky: ["#DBEAFE", "#86EFAC", "#22C55E", "#15803D"],
    mountain: ["#15803D", "#052E16"],
    ground: { stripeA: "#365314", stripeB: "#1E3008", base: "#142105", topBorder: "#0A1003" },
    decor: ["🪕", "🌿", "🍵", "🌸"],
    itemColor: "#15803D",
    bannerHighlight: "#FDE68A",
    loseHint: "¡Otra vez!",
    vocab: [
      { es: "iré",       en: "I will go" },
      { es: "comeré",    en: "I will eat" },
      { es: "hablaré",   en: "I will talk" },
      { es: "veré",      en: "I will see" },
      { es: "haré",      en: "I will do" },
      { es: "saldré",    en: "I will leave" },
      { es: "vendré",    en: "I will come" },
      { es: "tendré",    en: "I will have" },
      { es: "diré",      en: "I will say" },
      { es: "podré",     en: "I will be able" },
    ],
  },
  "Uruguay": {
    worldName: "Montevideo Rambla",  // Uruguay (not provided by user; kept default)
    sky: ["#BAE6FD", "#7DD3FC", "#0EA5E9", "#075985"],
    mountain: ["#0F172A", "#020617"],
    ground: { stripeA: "#FDE68A", stripeB: "#FCD34D", base: "#D97706", topBorder: "#78350F" },
    decor: ["🥁", "🧉", "🌊", "🐎"],
    itemColor: "#0EA5E9",
    bannerHighlight: "#FEF3C7",
    loseHint: "¡Otra vez!",
    vocab: [
      { es: "iría",      en: "I would go" },
      { es: "comería",   en: "I would eat" },
      { es: "hablaría",  en: "I would talk" },
      { es: "vería",     en: "I would see" },
      { es: "haría",     en: "I would do" },
      { es: "saldría",   en: "I would leave" },
      { es: "vendría",   en: "I would come" },
      { es: "tendría",   en: "I would have" },
      { es: "diría",     en: "I would say" },
      { es: "podría",    en: "I would be able" },
    ],
  },
  "Chile": {
    worldName: "Valparaíso",
    sky: ["#E0F2FE", "#7DD3FC", "#0284C7", "#0C4A6E"],
    mountain: ["#3F3F46", "#18181B"],
    ground: { stripeA: "#A8A29E", stripeB: "#78716C", base: "#44403C", topBorder: "#1C1917" },
    decor: ["🏔️", "🍷", "🐧", "🌊"],
    itemColor: "#0284C7",
    bannerHighlight: "#FDE68A",
    loseHint: "¡Otra vez!",
    vocab: [
      { es: "yo",        en: "I" },
      { es: "tú",        en: "you" },
      { es: "él",        en: "he" },
      { es: "ella",      en: "she" },
      { es: "nosotros",  en: "we" },
      { es: "ustedes",   en: "you all" },
      { es: "ellos",     en: "they (m)" },
      { es: "ellas",     en: "they (f)" },
      { es: "vosotros",  en: "you all (Spain)" },
      { es: "uno",       en: "one (impersonal)" },
    ],
  },
  "Argentina": {
    worldName: "Iguazú Falls",
    sky: ["#FECACA", "#F472B6", "#7C3AED", "#1E1B4B"],
    mountain: ["#1E1B4B", "#0F0A30"],
    ground: { stripeA: "#7F1D1D", stripeB: "#581C18", base: "#3A1010", topBorder: "#1A0606" },
    decor: ["💃", "🎻", "🥩", "🌹"],
    itemColor: "#7C3AED",
    bannerHighlight: "#FDE68A",
    loseHint: "¡Otra vez, ché!",
    vocab: [
      { es: "haber",       en: "to have (aux)" },
      { es: "ser",         en: "to be (essence)" },
      { es: "estar",       en: "to be (state)" },
      { es: "deber",       en: "should" },
      { es: "poder",       en: "can" },
      { es: "querer",      en: "to want" },
      { es: "necesitar",   en: "to need" },
      { es: "preferir",    en: "to prefer" },
      { es: "esperar",     en: "to hope/wait" },
      { es: "intentar",    en: "to try" },
    ],
  },
  // Default fallback for any country without a curated theme
  "Latin America": {
    worldName: "Bonus World",
    sky: ["#FEF3C7", "#FBBF24", "#F97316", "#9A3412"],
    mountain: ["#7C2D12", "#451A03"],
    ground: baseGround,
    decor: ["🌎", "🎺", "🌴", "⭐"],
    itemColor: "#0A75D3",
    bannerHighlight: "#FDE68A",
    loseHint: "¡Otra vez!",
    vocab: [
      { es: "hola",     en: "hello" },
      { es: "adiós",    en: "goodbye" },
      { es: "gracias",  en: "thank you" },
      { es: "por favor",en: "please" },
      { es: "sí",       en: "yes" },
      { es: "no",       en: "no" },
      { es: "amigo",    en: "friend" },
      { es: "agua",     en: "water" },
    ],
  },
}

export const getCountryTheme = (country: string): CountryTheme =>
  COUNTRY_THEMES[country] ?? COUNTRY_THEMES["Latin America"]
