// Centralized per-song fly word data for all songs (1-50)
// Each song maps to its own vocabulary set for the per-song Fly game

import type { FlyPhaseConfig } from "@/components/vocab-fly"

export interface FlyWord { spanish: string; english: string }

export interface SongFlyEntry {
  songNumber: number
  title: string
  icon: string
  phaseConfig: FlyPhaseConfig
  accentColor: string
  isAlphabet?: boolean
  alphabetFilter?: (entry: { label: string; category: string }) => boolean
}

export const SONG_FLY_DATA: Record<number, SongFlyEntry> = {
  // ═══════════════════════════════════════════════════════════════
  // ALPHABET WORLD (Songs 1-3) — letter-based, uses AlphabetFly
  // ═══════════════════════════════════════════════════════════════
  1: {
    songNumber: 1,
    title: "El Abecedario",
    icon: "📚",
    isAlphabet: true,
    // No filter — all 27 letters
    phaseConfig: {
      words: [],
      speedBase: 0.28, speedVariance: 0.10, waveInterval: 4200,
      label: "A – Z",
      bgGradient: "linear-gradient(180deg,#1a0f00 0%,#78350f 30%,#b45309 65%,#f59e0b 100%)",
      bubbleBg: "#fef3c7", bubbleText: "#92400e",
      progressGrad: "linear-gradient(90deg,#fbbf24,#f59e0b)",
      badgeColor: "rgba(180,83,9,0.5)",
    },
    accentColor: "linear-gradient(135deg,#f59e0b,#d97706)",
  },
  2: {
    songNumber: 2,
    title: "Ñ, CH, RR, LL",
    icon: "📚",
    isAlphabet: true,
    alphabetFilter: (entry) => entry.category === "special",
    phaseConfig: {
      words: [],
      speedBase: 0.26, speedVariance: 0.08, waveInterval: 4500,
      label: "Special Letters",
      bgGradient: "linear-gradient(180deg,#1a0f00 0%,#78350f 30%,#b45309 65%,#f59e0b 100%)",
      bubbleBg: "#fef3c7", bubbleText: "#92400e",
      progressGrad: "linear-gradient(90deg,#fbbf24,#f59e0b)",
      badgeColor: "rgba(180,83,9,0.5)",
    },
    accentColor: "linear-gradient(135deg,#f59e0b,#d97706)",
  },
  3: {
    songNumber: 3,
    title: "A, E, I, O, U",
    icon: "📚",
    isAlphabet: true,
    alphabetFilter: (entry) => entry.category === "vowel",
    phaseConfig: {
      words: [],
      speedBase: 0.26, speedVariance: 0.08, waveInterval: 4500,
      label: "Vowels",
      bgGradient: "linear-gradient(180deg,#1a0f00 0%,#78350f 30%,#b45309 65%,#f59e0b 100%)",
      bubbleBg: "#fef3c7", bubbleText: "#92400e",
      progressGrad: "linear-gradient(90deg,#fbbf24,#f59e0b)",
      badgeColor: "rgba(180,83,9,0.5)",
    },
    accentColor: "linear-gradient(135deg,#f59e0b,#d97706)",
  },

  // ═══════════════════════════════════════════════════════════════
  // BODY WORLD (Songs 4-5)
  // ═══════════════════════════════════════════════════════════════
  4: {
    songNumber: 4,
    title: "Body Parts Fly",
    icon: "🧍",
    phaseConfig: {
      words: [
        { spanish: "cabeza",   english: "head"      },
        { spanish: "pelo",     english: "hair"      },
        { spanish: "cuello",   english: "neck"      },
        { spanish: "garganta", english: "throat"    },
        { spanish: "hombros",  english: "shoulders" },
        { spanish: "brazos",   english: "arms"      },
        { spanish: "codos",    english: "elbows"    },
        { spanish: "manos",    english: "hands"     },
        { spanish: "espalda",  english: "back"      },
        { spanish: "barriga",  english: "belly"     },
        { spanish: "pierna",   english: "leg"       },
        { spanish: "rodilla",  english: "knee"      },
        { spanish: "pies",     english: "feet"      },
        { spanish: "ojos",     english: "eyes"      },
        { spanish: "nariz",    english: "nose"      },
        { spanish: "labios",   english: "lips"      },
        { spanish: "dientes",  english: "teeth"     },
        { spanish: "oreja",    english: "ear"       },
        { spanish: "boca",     english: "mouth"     },
        { spanish: "lengua",   english: "tongue"    },
        { spanish: "frente",   english: "forehead"  },
        { spanish: "cuerpo",   english: "body"      },
        { spanish: "cara",     english: "face"      },
        { spanish: "dedos",    english: "fingers"   },
        { spanish: "muñecas",  english: "wrists"    },
      ],
      speedBase: 0.28, speedVariance: 0.10, waveInterval: 4200,
      label: "Body Parts",
      bgGradient: "linear-gradient(180deg,#1a0020 0%,#3b0764 30%,#6d28d9 65%,#a78bfa 100%)",
      bubbleBg: "#ede9fe", bubbleText: "#5b21b6",
      progressGrad: "linear-gradient(90deg,#a78bfa,#7c3aed)",
      badgeColor: "rgba(91,33,182,0.5)",
    },
    accentColor: "linear-gradient(135deg,#7c3aed,#6d28d9)",
  },
  5: {
    songNumber: 5,
    title: "Clothing Fly",
    icon: "👕",
    phaseConfig: {
      words: [
        { spanish: "ropa",      english: "clothes"  },
        { spanish: "camisa",    english: "shirt"    },
        { spanish: "pantalón",  english: "pants"    },
        { spanish: "zapatos",   english: "shoes"    },
        { spanish: "cinturón",  english: "belt"     },
        { spanish: "gorra",     english: "cap"      },
        { spanish: "guantes",   english: "gloves"   },
        { spanish: "calcetín",  english: "sock"     },
        { spanish: "falda",     english: "skirt"    },
        { spanish: "suéter",    english: "sweater"  },
        { spanish: "chaqueta",  english: "jacket"   },
        { spanish: "bufanda",   english: "scarf"    },
        { spanish: "traje",     english: "suit"     },
        { spanish: "vestido",   english: "dress"    },
        { spanish: "pijama",    english: "pajamas"  },
        { spanish: "botas",     english: "boots"    },
        { spanish: "sandalias", english: "sandals"  },
      ],
      speedBase: 0.30, speedVariance: 0.10, waveInterval: 4000,
      label: "Clothing",
      bgGradient: "linear-gradient(180deg,#1a0028 0%,#4a044e 30%,#86198f 65%,#d946ef 100%)",
      bubbleBg: "#fae8ff", bubbleText: "#86198f",
      progressGrad: "linear-gradient(90deg,#e879f9,#d946ef)",
      badgeColor: "rgba(134,25,143,0.5)",
    },
    accentColor: "linear-gradient(135deg,#d946ef,#86198f)",
  },

  // ═══════════════════════════════════════════════════════════════
  // ROLES WORLD (Songs 6-7)
  // ═══════════════════════════════════════════════════════════════
  6: {
    songNumber: 6,
    title: "Family Fly",
    icon: "👨‍👩‍👧",
    phaseConfig: {
      words: [
        { spanish: "familia",  english: "family"     },
        { spanish: "papá",     english: "dad"        },
        { spanish: "mamá",     english: "mom"        },
        { spanish: "hermano",  english: "brother"    },
        { spanish: "hermana",  english: "sister"     },
        { spanish: "tío",      english: "uncle"      },
        { spanish: "tía",      english: "aunt"       },
        { spanish: "abuela",   english: "grandma"    },
        { spanish: "abuelo",   english: "grandpa"    },
        { spanish: "primo",    english: "cousin (m)" },
        { spanish: "prima",    english: "cousin (f)" },
        { spanish: "sobrino",  english: "nephew"     },
        { spanish: "sobrina",  english: "niece"      },
        { spanish: "mascota",  english: "pet"        },
      ],
      speedBase: 0.28, speedVariance: 0.10, waveInterval: 4200,
      label: "Mi Familia",
      bgGradient: "linear-gradient(180deg,#1c0500 0%,#7c2d12 30%,#c2410c 65%,#fb923c 100%)",
      bubbleBg: "#fed7aa", bubbleText: "#9a3412",
      progressGrad: "linear-gradient(90deg,#fb923c,#ea580c)",
      badgeColor: "rgba(154,52,18,0.5)",
    },
    accentColor: "linear-gradient(135deg,#ea580c,#c2410c)",
  },
  7: {
    songNumber: 7,
    title: "Jobs Fly",
    icon: "👷",
    phaseConfig: {
      words: [
        { spanish: "doctor",      english: "doctor"         },
        { spanish: "bombero",     english: "firefighter"    },
        { spanish: "panadero",    english: "baker"          },
        { spanish: "maestra",     english: "teacher"        },
        { spanish: "piloto",      english: "pilot"          },
        { spanish: "carpintero",  english: "carpenter"      },
        { spanish: "cantante",    english: "singer"         },
        { spanish: "chef",        english: "chef"           },
        { spanish: "jardinero",   english: "gardener"       },
        { spanish: "dentista",    english: "dentist"        },
        { spanish: "artista",     english: "artist"         },
        { spanish: "ingeniero",   english: "engineer"       },
        { spanish: "policía",     english: "police officer" },
        { spanish: "granjero",    english: "farmer"         },
        { spanish: "pintor",      english: "painter"        },
        { spanish: "actor",       english: "actor"          },
        { spanish: "enfermera",   english: "nurse"          },
        { spanish: "escritor",    english: "writer"         },
        { spanish: "veterinario", english: "vet"            },
        { spanish: "conductor",   english: "driver"         },
        { spanish: "arquitecto",  english: "architect"      },
        { spanish: "traductor",   english: "translator"     },
        { spanish: "profesión",  english: "profession"     },
        { spanish: "trabajos",   english: "jobs"           },
      ],
      speedBase: 0.30, speedVariance: 0.12, waveInterval: 3800,
      label: "Jobs",
      bgGradient: "linear-gradient(180deg,#0a1628 0%,#1e3a8a 30%,#2563eb 65%,#60a5fa 100%)",
      bubbleBg: "#bfdbfe", bubbleText: "#1d4ed8",
      progressGrad: "linear-gradient(90deg,#60a5fa,#2563eb)",
      badgeColor: "rgba(29,78,216,0.5)",
    },
    accentColor: "linear-gradient(135deg,#2563eb,#1e3a8a)",
  },

  // ═══════════════════════════════════════════════════════════════
  // PET WORLD (Songs 8-10)
  // ═══════════════════════════════════════════════════════════════
  8: {
    songNumber: 8,
    title: "Animals Fly",
    icon: "🦁",
    phaseConfig: {
      words: [
        { spanish: "araña",     english: "spider"      },
        { spanish: "elefante",  english: "elephant"    },
        { spanish: "iguana",    english: "iguana"      },
        { spanish: "oso",       english: "bear"        },
        { spanish: "unicornio", english: "unicorn"     },
        { spanish: "búho",      english: "owl"         },
        { spanish: "conejo",    english: "rabbit"      },
        { spanish: "delfín",    english: "dolphin"     },
        { spanish: "flamenco",  english: "flamingo"    },
        { spanish: "gato",      english: "cat"         },
        { spanish: "jirafa",    english: "giraffe"     },
        { spanish: "koala",     english: "koala"       },
        { spanish: "león",      english: "lion"        },
        { spanish: "mono",      english: "monkey"      },
        { spanish: "pingüino",  english: "penguin"     },
        { spanish: "tigre",     english: "tiger"       },
        { spanish: "vaca",      english: "cow"         },
        { spanish: "zorro",       english: "fox"           },
        { spanish: "chivo",       english: "goat"          },
        { spanish: "hipopótamo",  english: "hippopotamus"  },
        { spanish: "nutria",      english: "otter"         },
        { spanish: "serpiente",   english: "snake"         },
        { spanish: "animales",    english: "animals"       },
      ],
      speedBase: 0.26, speedVariance: 0.10, waveInterval: 4200,
      label: "Animals",
      bgGradient: "linear-gradient(180deg,#0c1a33 0%,#0a3d52 30%,#0e7490 65%,#06b6d4 100%)",
      bubbleBg: "#a5f3fc", bubbleText: "#0e7490",
      progressGrad: "linear-gradient(90deg,#22d3ee,#06b6d4)",
      badgeColor: "rgba(6,182,212,0.45)",
    },
    accentColor: "linear-gradient(135deg,#06b6d4,#0891b2)",
  },
  9: {
    songNumber: 9,
    title: "Pets Fly",
    icon: "🐾",
    phaseConfig: {
      words: [
        { spanish: "perro",   english: "dog"     },
        { spanish: "gato",    english: "cat"     },
        { spanish: "conejo",  english: "rabbit"  },
        { spanish: "pato",    english: "duck"    },
        { spanish: "vaca",    english: "cow"     },
        { spanish: "oveja",   english: "sheep"   },
        { spanish: "gallina", english: "hen"     },
        { spanish: "caballo", english: "horse"   },
        { spanish: "cabra",   english: "goat"    },
        { spanish: "tortuga",  english: "turtle"  },
        { spanish: "mascotas", english: "pets"    },
      ],
      speedBase: 0.28, speedVariance: 0.10, waveInterval: 4200,
      label: "Pets",
      bgGradient: "linear-gradient(180deg,#0c1a33 0%,#0a3d52 30%,#0e7490 65%,#06b6d4 100%)",
      bubbleBg: "#a5f3fc", bubbleText: "#0e7490",
      progressGrad: "linear-gradient(90deg,#22d3ee,#06b6d4)",
      badgeColor: "rgba(6,182,212,0.45)",
    },
    accentColor: "linear-gradient(135deg,#06b6d4,#0891b2)",
  },
  10: {
    songNumber: 10,
    title: "Habitats Fly",
    icon: "🌳",
    phaseConfig: {
      words: [
        { spanish: "agua",     english: "water"       },
        { spanish: "cielo",    english: "sky"         },
        { spanish: "bosque",   english: "forest"      },
        { spanish: "montaña",  english: "mountain"    },
        { spanish: "pez",      english: "fish"        },
        { spanish: "rana",     english: "frog"        },
        { spanish: "cangrejo", english: "crab"        },
        { spanish: "pájaro",   english: "bird"        },
        { spanish: "águila",   english: "eagle"       },
        { spanish: "abeja",    english: "bee"         },
        { spanish: "colibrí",  english: "hummingbird" },
        { spanish: "oso",      english: "bear"        },
        { spanish: "zorro",    english: "fox"         },
        { spanish: "ardilla",  english: "squirrel"    },
        { spanish: "araña",     english: "spider"    },
        { spanish: "ciempiés",  english: "centipede" },
        { spanish: "tortuga",   english: "turtle"    },
        { spanish: "animales",  english: "animals"   },
      ],
      speedBase: 0.30, speedVariance: 0.12, waveInterval: 3800,
      label: "Habitats",
      bgGradient: "linear-gradient(180deg,#0a1f0a 0%,#0f3b14 30%,#166534 65%,#22c55e 100%)",
      bubbleBg: "#bbf7d0", bubbleText: "#065f46",
      progressGrad: "linear-gradient(90deg,#4ade80,#22c55e)",
      badgeColor: "rgba(34,197,94,0.45)",
    },
    accentColor: "linear-gradient(135deg,#22c55e,#16a34a)",
  },

  // ═══════════════════════════════════════════════════════════════
  // TRAVEL WORLD (Songs 11-13)
  // ═══════════════════════════════════════════════════════════════
  11: {
    songNumber: 11,
    title: "My House Fly",
    icon: "🏠",
    phaseConfig: {
      words: [
        { spanish: "sillón",    english: "armchair" },
        { spanish: "taza",      english: "cup"      },
        { spanish: "mesa",      english: "table"    },
        { spanish: "sartén",    english: "pan"      },
        { spanish: "vitrina",   english: "cabinet"  },
        { spanish: "plato",     english: "plate"    },
        { spanish: "hornilla",  english: "stove"    },
        { spanish: "jabón",     english: "soap"     },
        { spanish: "toalla",    english: "towel"    },
        { spanish: "lavamanos", english: "sink"     },
        { spanish: "cama",      english: "bed"      },
        { spanish: "marco",     english: "frame"    },
        { spanish: "lámpara",   english: "lamp"     },
        { spanish: "zapato",    english: "shoe"     },
        { spanish: "casa",      english: "house"    },
        { spanish: "cocina",    english: "kitchen"  },
        { spanish: "baño",      english: "bathroom" },
        { spanish: "cuarto",    english: "room"     },
      ],
      speedBase: 0.28, speedVariance: 0.10, waveInterval: 4200,
      label: "My House",
      bgGradient: "linear-gradient(180deg,#0a1a1a 0%,#0a3030 30%,#0f5757 65%,#0d9488 100%)",
      bubbleBg: "#ccfbf1", bubbleText: "#0f766e",
      progressGrad: "linear-gradient(90deg,#2dd4bf,#0d9488)",
      badgeColor: "rgba(13,148,136,0.45)",
    },
    accentColor: "linear-gradient(135deg,#0d9488,#059669)",
  },
  12: {
    songNumber: 12,
    title: "Places Fly",
    icon: "📍",
    phaseConfig: {
      words: [
        { spanish: "baño",       english: "bathroom" },
        { spanish: "escuela",    english: "school"   },
        { spanish: "biblioteca", english: "library"  },
        { spanish: "playa",      english: "beach"    },
        { spanish: "parque",     english: "park"     },
        { spanish: "tienda",     english: "store"    },
        { spanish: "hospital",   english: "hospital" },
        { spanish: "panadería",  english: "bakery"   },
        { spanish: "cine",       english: "cinema"   },
        { spanish: "casa",       english: "home"    },
        { spanish: "lugares",    english: "places"  },
      ],
      speedBase: 0.28, speedVariance: 0.10, waveInterval: 4200,
      label: "Places",
      bgGradient: "linear-gradient(180deg,#0a1a0a 0%,#0a3020 30%,#065f46 65%,#059669 100%)",
      bubbleBg: "#a7f3d0", bubbleText: "#047857",
      progressGrad: "linear-gradient(90deg,#34d399,#059669)",
      badgeColor: "rgba(5,150,105,0.45)",
    },
    accentColor: "linear-gradient(135deg,#059669,#047857)",
  },
  13: {
    songNumber: 13,
    title: "Directions Fly",
    icon: "🧭",
    phaseConfig: {
      words: [
        { spanish: "izquierda", english: "left"    },
        { spanish: "derecha",   english: "right"   },
        { spanish: "arriba",    english: "up"      },
        { spanish: "abajo",     english: "down"    },
        { spanish: "delante",   english: "forward" },
        { spanish: "detrás",    english: "behind"  },
        { spanish: "cerca",     english: "near"    },
        { spanish: "lejos",        english: "far"        },
        { spanish: "gira",         english: "turn"       },
        { spanish: "vuelta",       english: "turn around" },
        { spanish: "direcciones",  english: "directions" },
      ],
      speedBase: 0.26, speedVariance: 0.08, waveInterval: 4500,
      label: "Directions",
      bgGradient: "linear-gradient(180deg,#0a1a0a 0%,#0a3020 30%,#065f46 65%,#059669 100%)",
      bubbleBg: "#a7f3d0", bubbleText: "#047857",
      progressGrad: "linear-gradient(90deg,#34d399,#059669)",
      badgeColor: "rgba(5,150,105,0.45)",
    },
    accentColor: "linear-gradient(135deg,#059669,#047857)",
  },

  // ═══════════════════════════════════════════════════════════════
  // NUMBERS WORLD (Songs 14-15)
  // ═══════════════════════════════════════════════════════════════
  14: {
    songNumber: 14,
    title: "Numbers 1-20 Fly",
    icon: "🔢",
    phaseConfig: {
      words: [
        { spanish: "uno",        english: "one"       },
        { spanish: "dos",        english: "two"       },
        { spanish: "tres",       english: "three"     },
        { spanish: "cuatro",     english: "four"      },
        { spanish: "cinco",      english: "five"      },
        { spanish: "seis",       english: "six"       },
        { spanish: "siete",      english: "seven"     },
        { spanish: "ocho",       english: "eight"     },
        { spanish: "nueve",      english: "nine"      },
        { spanish: "diez",       english: "ten"       },
        { spanish: "once",       english: "eleven"    },
        { spanish: "doce",       english: "twelve"    },
        { spanish: "trece",      english: "thirteen"  },
        { spanish: "catorce",    english: "fourteen"  },
        { spanish: "quince",     english: "fifteen"   },
        { spanish: "dieciséis",  english: "sixteen"   },
        { spanish: "diecisiete", english: "seventeen" },
        { spanish: "dieciocho",  english: "eighteen"  },
        { spanish: "diecinueve", english: "nineteen"  },
        { spanish: "veinte",     english: "twenty"    },
      ],
      speedBase: 0.28, speedVariance: 0.10, waveInterval: 4200,
      label: "1 – 20",
      bgGradient: "linear-gradient(180deg,#1a0a33 0%,#2e1065 30%,#5b21b6 65%,#7c3aed 100%)",
      bubbleBg: "#ede9fe", bubbleText: "#5b21b6",
      progressGrad: "linear-gradient(90deg,#a78bfa,#7c3aed)",
      badgeColor: "rgba(91,33,182,0.5)",
    },
    accentColor: "linear-gradient(135deg,#7c3aed,#4338ca)",
  },
  15: {
    songNumber: 15,
    title: "Tens Fly",
    icon: "🔟",
    phaseConfig: {
      words: [
        { spanish: "diez",      english: "ten"         },
        { spanish: "veinte",    english: "twenty"      },
        { spanish: "treinta",   english: "thirty"      },
        { spanish: "cuarenta",  english: "forty"       },
        { spanish: "cincuenta", english: "fifty"       },
        { spanish: "sesenta",   english: "sixty"       },
        { spanish: "setenta",   english: "seventy"     },
        { spanish: "ochenta",   english: "eighty"      },
        { spanish: "noventa",   english: "ninety"      },
        { spanish: "cien",      english: "one hundred" },
      ],
      speedBase: 0.30, speedVariance: 0.10, waveInterval: 3800,
      label: "Tens",
      bgGradient: "linear-gradient(180deg,#0f0a2e 0%,#1e1b4b 30%,#312e81 65%,#4338ca 100%)",
      bubbleBg: "#e0e7ff", bubbleText: "#3730a3",
      progressGrad: "linear-gradient(90deg,#818cf8,#4338ca)",
      badgeColor: "rgba(67,56,202,0.5)",
    },
    accentColor: "linear-gradient(135deg,#4338ca,#312e81)",
  },

  // ═══════════════════════════════════════════════════════════════
  // TIME WORLD (Songs 16-17)
  // ═══════════════════════════════════════════════════════════════
  16: {
    songNumber: 16,
    title: "Days & Months Fly",
    icon: "📅",
    phaseConfig: {
      words: [
        { spanish: "lunes",      english: "Monday"    },
        { spanish: "martes",     english: "Tuesday"   },
        { spanish: "miércoles",  english: "Wednesday" },
        { spanish: "jueves",     english: "Thursday"  },
        { spanish: "viernes",    english: "Friday"    },
        { spanish: "sábado",     english: "Saturday"  },
        { spanish: "domingo",    english: "Sunday"    },
        { spanish: "enero",      english: "January"   },
        { spanish: "febrero",    english: "February"  },
        { spanish: "marzo",      english: "March"     },
        { spanish: "abril",      english: "April"     },
        { spanish: "mayo",       english: "May"       },
        { spanish: "junio",      english: "June"      },
        { spanish: "julio",      english: "July"      },
        { spanish: "agosto",     english: "August"    },
        { spanish: "septiembre", english: "September" },
        { spanish: "octubre",    english: "October"   },
        { spanish: "noviembre",  english: "November"  },
        { spanish: "diciembre",  english: "December"  },
        { spanish: "primavera",  english: "spring"    },
        { spanish: "verano",     english: "summer"    },
        { spanish: "otoño",      english: "fall"      },
        { spanish: "invierno",   english: "winter"    },
        { spanish: "días",       english: "days"      },
        { spanish: "semana",     english: "week"      },
        { spanish: "meses",      english: "months"    },
        { spanish: "estaciones", english: "seasons"   },
      ],
      speedBase: 0.26, speedVariance: 0.10, waveInterval: 4200,
      label: "Days & Months",
      bgGradient: "linear-gradient(180deg,#0a1535 0%,#0c2461 30%,#1e40af 65%,#3b82f6 100%)",
      bubbleBg: "#bfdbfe", bubbleText: "#1d4ed8",
      progressGrad: "linear-gradient(90deg,#60a5fa,#3b82f6)",
      badgeColor: "rgba(29,78,216,0.5)",
    },
    accentColor: "linear-gradient(135deg,#3b82f6,#1e40af)",
  },
  17: {
    songNumber: 17,
    title: "Telling Time Fly",
    icon: "🕐",
    phaseConfig: {
      words: [
        { spanish: "reloj",        english: "clock"         },
        { spanish: "la una",       english: "one o'clock"   },
        { spanish: "las dos",      english: "two o'clock"   },
        { spanish: "las tres",     english: "three o'clock" },
        { spanish: "las cuatro",   english: "four o'clock"  },
        { spanish: "las cinco",    english: "five o'clock"  },
        { spanish: "las seis",     english: "six o'clock"   },
        { spanish: "las siete",    english: "seven o'clock" },
        { spanish: "las ocho",     english: "eight o'clock" },
        { spanish: "las nueve",    english: "nine o'clock"  },
        { spanish: "las diez",     english: "ten o'clock"   },
        { spanish: "y cuarto",     english: "quarter past"  },
        { spanish: "y media",      english: "half past"     },
        { spanish: "en punto",     english: "on the dot"    },
        { spanish: "menos cuarto", english: "quarter to"    },
      ],
      speedBase: 0.28, speedVariance: 0.10, waveInterval: 3800,
      label: "Telling Time",
      bgGradient: "linear-gradient(180deg,#030714 0%,#0c1a33 30%,#1e3a5f 65%,#1d4ed8 100%)",
      bubbleBg: "#dbeafe", bubbleText: "#1e40af",
      progressGrad: "linear-gradient(90deg,#93c5fd,#1d4ed8)",
      badgeColor: "rgba(30,64,175,0.5)",
    },
    accentColor: "linear-gradient(135deg,#1d4ed8,#1e40af)",
  },

  // ═══════════════════════════════════════════════════════════════
  // FEELINGS COLOR WORLD (Songs 18-20)
  // ═══════════════════════════════════════════════════════════════
  18: {
    songNumber: 18,
    title: "Colors Fly",
    icon: "🎨",
    phaseConfig: {
      words: [
        { spanish: "rojo",      english: "red"       },
        { spanish: "naranja",   english: "orange"    },
        { spanish: "amarillo",  english: "yellow"    },
        { spanish: "verde",     english: "green"     },
        { spanish: "azul",      english: "blue"      },
        { spanish: "morado",    english: "purple"    },
        { spanish: "blanco",    english: "white"     },
        { spanish: "negro",     english: "black"     },
        { spanish: "gris",      english: "gray"      },
        { spanish: "colores",   english: "colors"    },
      ],
      speedBase: 0.28, speedVariance: 0.10, waveInterval: 4200,
      label: "Colors",
      bgGradient: "linear-gradient(180deg,#1a0a00 0%,#431407 30%,#9a3412 65%,#ea580c 100%)",
      bubbleBg: "#fed7aa", bubbleText: "#9a3412",
      progressGrad: "linear-gradient(90deg,#fb923c,#ea580c)",
      badgeColor: "rgba(154,52,18,0.5)",
      colorMap: {
        rojo:    "linear-gradient(180deg,#450a0a 0%,#7f1d1d 30%,#dc2626 70%,#f87171 100%)",
        naranja: "linear-gradient(180deg,#431407 0%,#9a3412 30%,#ea580c 70%,#fb923c 100%)",
        amarillo:"linear-gradient(180deg,#422006 0%,#713f12 30%,#ca8a04 70%,#fde047 100%)",
        verde:   "linear-gradient(180deg,#052e16 0%,#14532d 30%,#16a34a 70%,#4ade80 100%)",
        azul:    "linear-gradient(180deg,#172554 0%,#1e3a8a 30%,#2563eb 70%,#60a5fa 100%)",
        morado:  "linear-gradient(180deg,#2e1065 0%,#4c1d95 30%,#7c3aed 70%,#c084fc 100%)",
        blanco:  "linear-gradient(180deg,#1e293b 0%,#475569 30%,#94a3b8 70%,#e2e8f0 100%)",
        negro:   "linear-gradient(180deg,#000000 0%,#0f172a 30%,#1e293b 70%,#334155 100%)",
        gris:    "linear-gradient(180deg,#0f172a 0%,#1e293b 30%,#475569 70%,#94a3b8 100%)",
      },
    },
    accentColor: "linear-gradient(135deg,#ea580c,#dc2626)",
  },
  19: {
    songNumber: 19,
    title: "Feelings Fly",
    icon: "😊",
    phaseConfig: {
      words: [
        { spanish: "feliz",       english: "happy"     },
        { spanish: "triste",      english: "sad"       },
        { spanish: "enojado",     english: "angry"     },
        { spanish: "cansado",     english: "tired"     },
        { spanish: "sorprendido", english: "surprised" },
        { spanish: "aburrido",    english: "bored"     },
        { spanish: "contento",    english: "content"   },
        { spanish: "nervioso",      english: "nervous"   },
        { spanish: "sentimientos", english: "feelings"  },
      ],
      speedBase: 0.28, speedVariance: 0.10, waveInterval: 4200,
      label: "Feelings",
      bgGradient: "linear-gradient(180deg,#1a0033 0%,#4a0072 30%,#7e22ce 65%,#a855f7 100%)",
      bubbleBg: "#fbcfe8", bubbleText: "#9d174d",
      progressGrad: "linear-gradient(90deg,#e879f9,#a855f7)",
      badgeColor: "rgba(126,34,206,0.5)",
    },
    accentColor: "linear-gradient(135deg,#a855f7,#7e22ce)",
  },
  20: {
    songNumber: 20,
    title: "Needs Fly",
    icon: "💧",
    phaseConfig: {
      words: [
        { spanish: "sed",       english: "thirsty"    },
        { spanish: "hambre",    english: "hungry"     },
        { spanish: "frío",      english: "cold"       },
        { spanish: "calor",     english: "hot"        },
        { spanish: "miedo",     english: "afraid"     },
        { spanish: "sueño",     english: "sleepy"     },
        { spanish: "prisa",     english: "in a hurry" },
        { spanish: "tos",       english: "cough"      },
      ],
      speedBase: 0.26, speedVariance: 0.08, waveInterval: 4500,
      label: "Needs",
      bgGradient: "linear-gradient(180deg,#1a0033 0%,#4a0072 30%,#7e22ce 65%,#a855f7 100%)",
      bubbleBg: "#fbcfe8", bubbleText: "#9d174d",
      progressGrad: "linear-gradient(90deg,#e879f9,#a855f7)",
      badgeColor: "rgba(126,34,206,0.5)",
    },
    accentColor: "linear-gradient(135deg,#a855f7,#7e22ce)",
  },

  // ═══════════════════════════════════════════════════════════════
  // FOOD WORLD (Songs 21-23)
  // ═══════════════════════════════════════════════════════════════
  21: {
    songNumber: 21,
    title: "Fruits Fly",
    icon: "🍎",
    phaseConfig: {
      words: [
        { spanish: "manzana",   english: "apple"      },
        { spanish: "frutilla",  english: "strawberry" },
        { spanish: "naranja",   english: "orange"     },
        { spanish: "papaya",    english: "papaya"     },
        { spanish: "sandía",    english: "watermelon" },
        { spanish: "durazno",   english: "peach"      },
        { spanish: "banana",    english: "banana"     },
        { spanish: "melón",     english: "melon"      },
        { spanish: "piña",      english: "pineapple"  },
        { spanish: "pera",      english: "pear"       },
        { spanish: "guayaba",   english: "guava"      },
        { spanish: "uva",       english: "grape"      },
        { spanish: "ciruela",   english: "plum"       },
        { spanish: "mora",      english: "blueberry"  },
        { spanish: "arándano",  english: "cranberry"  },
        { spanish: "higo",      english: "fig"        },
        { spanish: "tamarindo", english: "tamarind"   },
        { spanish: "frutas",    english: "fruits"     },
      ],
      speedBase: 0.28, speedVariance: 0.10, waveInterval: 4200,
      label: "Fruits",
      bgGradient: "linear-gradient(180deg,#1a0f00 0%,#451a03 30%,#92400e 65%,#d97706 100%)",
      bubbleBg: "#fef3c7", bubbleText: "#92400e",
      progressGrad: "linear-gradient(90deg,#fbbf24,#d97706)",
      badgeColor: "rgba(146,64,14,0.5)",
    },
    accentColor: "linear-gradient(135deg,#d97706,#b45309)",
  },
  22: {
    songNumber: 22,
    title: "Vegetables Fly",
    icon: "🥦",
    phaseConfig: {
      words: [
        { spanish: "tomate",    english: "tomato"   },
        { spanish: "pimiento",  english: "pepper"   },
        { spanish: "zanahoria", english: "carrot"   },
        { spanish: "maíz",      english: "corn"     },
        { spanish: "papa",      english: "potato"   },
        { spanish: "lechuga",   english: "lettuce"  },
        { spanish: "berenjena", english: "eggplant" },
        { spanish: "cebolla",   english: "onion"    },
        { spanish: "acelga",    english: "chard"    },
        { spanish: "verduras",  english: "vegetables" },
      ],
      speedBase: 0.28, speedVariance: 0.10, waveInterval: 4200,
      label: "Vegetables",
      bgGradient: "linear-gradient(180deg,#0a1f0a 0%,#14401a 30%,#166534 65%,#16a34a 100%)",
      bubbleBg: "#bbf7d0", bubbleText: "#065f46",
      progressGrad: "linear-gradient(90deg,#4ade80,#16a34a)",
      badgeColor: "rgba(22,163,74,0.5)",
    },
    accentColor: "linear-gradient(135deg,#16a34a,#15803d)",
  },
  23: {
    songNumber: 23,
    title: "Meals Fly",
    icon: "🍽️",
    phaseConfig: {
      words: [
        { spanish: "leche",   english: "milk"    },
        { spanish: "pan",     english: "bread"   },
        { spanish: "huevo",   english: "egg"     },
        { spanish: "sopa",    english: "soup"    },
        { spanish: "arroz",   english: "rice"    },
        { spanish: "pollo",   english: "chicken" },
        { spanish: "pasta",   english: "pasta"   },
        { spanish: "pescado", english: "fish"    },
        { spanish: "avena",     english: "oatmeal"   },
        { spanish: "desayuno",  english: "breakfast"  },
        { spanish: "almuerzo",  english: "lunch"      },
        { spanish: "cena",      english: "dinner"     },
        { spanish: "mañana",    english: "morning"    },
        { spanish: "tarde",     english: "afternoon"  },
        { spanish: "noche",     english: "night"      },
        { spanish: "ensalada",  english: "salad"      },
        { spanish: "comidas",   english: "meals"      },
      ],
      speedBase: 0.28, speedVariance: 0.10, waveInterval: 4200,
      label: "Meals",
      bgGradient: "linear-gradient(180deg,#1a0f00 0%,#451a03 30%,#92400e 65%,#d97706 100%)",
      bubbleBg: "#fef3c7", bubbleText: "#92400e",
      progressGrad: "linear-gradient(90deg,#fbbf24,#d97706)",
      badgeColor: "rgba(146,64,14,0.5)",
    },
    accentColor: "linear-gradient(135deg,#d97706,#b45309)",
  },

  // ═══════════════════════════════════════════════════════════════
  // VERB GALAXY — AR World (Songs 24-27)
  // ═══════════════════════════════════════════════════════════════
  24: {
    songNumber: 24,
    title: "Restaurant Fly",
    icon: "🍽️",
    phaseConfig: {
      words: [
        { spanish: "hola",       english: "hello"           },
        { spanish: "gracias",    english: "thank you"       },
        { spanish: "por favor",  english: "please"          },
        { spanish: "pedir",      english: "to order"        },
        { spanish: "jugo",       english: "juice"           },
        { spanish: "arroz",      english: "rice"            },
        { spanish: "tenedor",    english: "fork"            },
        { spanish: "cuchillo",   english: "knife"           },
        { spanish: "plato",      english: "plate"           },
        { spanish: "cuchara",    english: "spoon"           },
        { spanish: "sopa",       english: "soup"            },
        { spanish: "servilleta", english: "napkin"          },
        { spanish: "cenar",      english: "to dine"         },
        { spanish: "terminar",    english: "to finish"    },
        { spanish: "restaurante", english: "restaurant"  },
      ],
      speedBase: 0.28, speedVariance: 0.10, waveInterval: 4200,
      label: "Restaurant",
      bgGradient: "linear-gradient(180deg,#021a2e 0%,#0c4a6e 30%,#0284c7 65%,#22d3ee 100%)",
      bubbleBg: "#cffafe", bubbleText: "#0e7490",
      progressGrad: "linear-gradient(90deg,#22d3ee,#0284c7)",
      badgeColor: "rgba(2,132,199,0.5)",
    },
    accentColor: "linear-gradient(135deg,#22d3ee,#0284c7)",
  },
  25: {
    songNumber: 25,
    title: "AR Verbs Fly",
    icon: "🅰️",
    phaseConfig: {
      words: [
        { spanish: "hablar",    english: "to speak"   },
        { spanish: "bailar",    english: "to dance"   },
        { spanish: "cantar",    english: "to sing"    },
        { spanish: "estudiar",  english: "to study"   },
        { spanish: "jugar",     english: "to play"    },
        { spanish: "trabajar",  english: "to work"    },
        { spanish: "nadar",     english: "to swim"    },
        { spanish: "dibujar",   english: "to draw"    },
        { spanish: "ayudar",    english: "to help"    },
        { spanish: "caminar",   english: "to walk"    },
        { spanish: "escuchar",  english: "to listen"  },
        { spanish: "yo",        english: "I"          },
        { spanish: "tú",        english: "you"        },
        { spanish: "él",        english: "he"         },
        { spanish: "ella",      english: "she"        },
        { spanish: "nosotros",  english: "we"         },
        { spanish: "ellos",     english: "they"       },
      ],
      speedBase: 0.28, speedVariance: 0.10, waveInterval: 4200,
      label: "AR Verbs",
      bgGradient: "linear-gradient(180deg,#021a2e 0%,#0c4a6e 30%,#0284c7 65%,#22d3ee 100%)",
      bubbleBg: "#cffafe", bubbleText: "#0e7490",
      progressGrad: "linear-gradient(90deg,#22d3ee,#0284c7)",
      badgeColor: "rgba(2,132,199,0.5)",
    },
    accentColor: "linear-gradient(135deg,#22d3ee,#0284c7)",
  },
  26: {
    songNumber: 26,
    title: "Gustar Fly",
    icon: "❤️",
    phaseConfig: {
      words: [
        { spanish: "gustar",      english: "to like"      },
        { spanish: "me",          english: "to me"        },
        { spanish: "te",          english: "to you"       },
        { spanish: "le",          english: "to him/her"   },
        { spanish: "nos",         english: "to us"        },
        { spanish: "les",         english: "to them"      },
        { spanish: "cantar",      english: "to sing"      },
        { spanish: "bailar",      english: "to dance"     },
        { spanish: "comer",       english: "to eat"       },
        { spanish: "correr",      english: "to run"       },
        { spanish: "chocolate",   english: "chocolate"    },
        { spanish: "tomate",      english: "tomato"       },
        { spanish: "lechuga",     english: "lettuce"      },
        { spanish: "frutas",      english: "fruits"       },
        { spanish: "verduras",    english: "vegetables"   },
        { spanish: "ojos",        english: "eyes"         },
        { spanish: "nariz",       english: "nose"         },
        { spanish: "camisa",      english: "shirt"        },
        { spanish: "pantalones",  english: "pants"        },
        { spanish: "zapatos",     english: "shoes"        },
      ],
      speedBase: 0.30, speedVariance: 0.10, waveInterval: 4000,
      label: "Gustar",
      bgGradient: "linear-gradient(180deg,#021a2e 0%,#0c4a6e 30%,#0284c7 65%,#22d3ee 100%)",
      bubbleBg: "#cffafe", bubbleText: "#0e7490",
      progressGrad: "linear-gradient(90deg,#22d3ee,#0284c7)",
      badgeColor: "rgba(2,132,199,0.5)",
    },
    accentColor: "linear-gradient(135deg,#22d3ee,#0284c7)",
  },
  27: {
    songNumber: 27,
    title: "Estar Fly",
    icon: "📍",
    phaseConfig: {
      words: [
        { spanish: "estoy",     english: "I am"      },
        { spanish: "estás",     english: "you are"   },
        { spanish: "está",      english: "he/she is" },
        { spanish: "estamos",   english: "we are"    },
        { spanish: "están",     english: "they are"  },
        { spanish: "feliz",     english: "happy"     },
        { spanish: "enfermo",   english: "sick"      },
        { spanish: "nerviosa",  english: "nervous"   },
        { spanish: "cansados",  english: "tired"     },
        { spanish: "contentos", english: "content"   },
        { spanish: "enojados",  english: "angry"     },
        { spanish: "aburridos", english: "bored"     },
        { spanish: "aquí",      english: "here"      },
        { spanish: "allí",      english: "there"     },
        { spanish: "tren",      english: "train"     },
      ],
      speedBase: 0.28, speedVariance: 0.10, waveInterval: 4200,
      label: "Estar",
      bgGradient: "linear-gradient(180deg,#021a2e 0%,#0c4a6e 30%,#0284c7 65%,#22d3ee 100%)",
      bubbleBg: "#cffafe", bubbleText: "#0e7490",
      progressGrad: "linear-gradient(90deg,#22d3ee,#0284c7)",
      badgeColor: "rgba(2,132,199,0.5)",
    },
    accentColor: "linear-gradient(135deg,#22d3ee,#0284c7)",
  },

  // ═══════════════════════════════════════════════════════════════
  // VERB GALAXY — ER World (Songs 28-30)
  // ═══════════════════════════════════════════════════════════════
  28: {
    songNumber: 28,
    title: "ER Verbs Fly",
    icon: "🅴",
    phaseConfig: {
      words: [
        { spanish: "beber",     english: "to drink"  },
        { spanish: "comer",     english: "to eat"    },
        { spanish: "leer",      english: "to read"   },
        { spanish: "aprender",  english: "to learn"  },
        { spanish: "correr",    english: "to run"    },
      ],
      speedBase: 0.28, speedVariance: 0.10, waveInterval: 4200,
      label: "ER Verbs",
      bgGradient: "linear-gradient(180deg,#021a10 0%,#064e3b 30%,#059669 65%,#4ade80 100%)",
      bubbleBg: "#d1fae5", bubbleText: "#065f46",
      progressGrad: "linear-gradient(90deg,#4ade80,#16a34a)",
      badgeColor: "rgba(22,163,74,0.5)",
    },
    accentColor: "linear-gradient(135deg,#4ade80,#16a34a)",
  },
  29: {
    songNumber: 29,
    title: "Tener Que Fly",
    icon: "💪",
    phaseConfig: {
      words: [
        { spanish: "tengo que",   english: "I have to"        },
        { spanish: "tienes que",  english: "you have to"      },
        { spanish: "tiene que",   english: "he/she has to"    },
        { spanish: "tenemos que", english: "we have to"       },
        { spanish: "tienen que",  english: "they have to"     },
        { spanish: "leer",        english: "to read"          },
        { spanish: "saltar",      english: "to jump"          },
        { spanish: "pensar",      english: "to think"         },
        { spanish: "ayudar",      english: "to help"          },
        { spanish: "escuchar",    english: "to listen"        },
        { spanish: "trabajar",    english: "to work"          },
      ],
      speedBase: 0.28, speedVariance: 0.10, waveInterval: 4200,
      label: "Tener Que",
      bgGradient: "linear-gradient(180deg,#021a10 0%,#064e3b 30%,#059669 65%,#4ade80 100%)",
      bubbleBg: "#d1fae5", bubbleText: "#065f46",
      progressGrad: "linear-gradient(90deg,#4ade80,#16a34a)",
      badgeColor: "rgba(22,163,74,0.5)",
    },
    accentColor: "linear-gradient(135deg,#4ade80,#16a34a)",
  },
  30: {
    songNumber: 30,
    title: "Ser Fly",
    icon: "🌟",
    phaseConfig: {
      words: [
        { spanish: "soy",         english: "I am"           },
        { spanish: "eres",        english: "you are"        },
        { spanish: "es",          english: "he/she is"      },
        { spanish: "somos",       english: "we are"         },
        { spanish: "son",         english: "they are"       },
        { spanish: "estudiante",  english: "student"        },
        { spanish: "cocinero",    english: "cook"           },
        { spanish: "artista",     english: "artist"         },
        { spanish: "amiga",       english: "friend"         },
        { spanish: "suave",       english: "soft"           },
        { spanish: "ser",         english: "to be"          },
      ],
      speedBase: 0.28, speedVariance: 0.10, waveInterval: 4200,
      label: "Ser",
      bgGradient: "linear-gradient(180deg,#021a10 0%,#064e3b 30%,#059669 65%,#4ade80 100%)",
      bubbleBg: "#d1fae5", bubbleText: "#065f46",
      progressGrad: "linear-gradient(90deg,#4ade80,#16a34a)",
      badgeColor: "rgba(22,163,74,0.5)",
    },
    accentColor: "linear-gradient(135deg,#4ade80,#16a34a)",
  },

  // ═══════════════════════════════════════════════════════════════
  // VERB GALAXY — IR World (Songs 31-33)
  // ═══════════════════════════════════════════════════════════════
  31: {
    songNumber: 31,
    title: "IR Verbs Fly",
    icon: "🅸",
    phaseConfig: {
      words: [
        { spanish: "vivir",    english: "to live"    },
        { spanish: "escribir", english: "to write"   },
        { spanish: "abrir",    english: "to open"    },
        { spanish: "asistir",  english: "to attend"  },
        { spanish: "decidir",  english: "to decide"  },
      ],
      speedBase: 0.28, speedVariance: 0.10, waveInterval: 4200,
      label: "IR Verbs",
      bgGradient: "linear-gradient(180deg,#1a0030 0%,#4c1d95 30%,#7c3aed 65%,#c084fc 100%)",
      bubbleBg: "#ede9fe", bubbleText: "#5b21b6",
      progressGrad: "linear-gradient(90deg,#c084fc,#9333ea)",
      badgeColor: "rgba(147,51,234,0.5)",
    },
    accentColor: "linear-gradient(135deg,#c084fc,#9333ea)",
  },
  32: {
    songNumber: 32,
    title: "Ir Fly",
    icon: "🚶",
    phaseConfig: {
      words: [
        { spanish: "voy",          english: "I go"             },
        { spanish: "vas",          english: "you go"           },
        { spanish: "va",           english: "he/she goes"      },
        { spanish: "vamos",        english: "we go"            },
        { spanish: "van",          english: "they go"          },
        { spanish: "parque",       english: "park"             },
        { spanish: "baño",         english: "bathroom"         },
        { spanish: "escuela",      english: "school"           },
        { spanish: "cuarto",       english: "room"             },
        { spanish: "cine",         english: "movie theater"    },
        { spanish: "mercado",      english: "market"           },
        { spanish: "playa",        english: "beach"            },
        { spanish: "restaurante",  english: "restaurant"       },
        { spanish: "biblioteca",   english: "library"          },
        { spanish: "fiesta",       english: "party"            },
        { spanish: "supermercado", english: "supermarket"      },
        { spanish: "gimnasio",     english: "gym"              },
        { spanish: "hospital",     english: "hospital"         },
        { spanish: "ir",           english: "to go"            },
      ],
      speedBase: 0.30, speedVariance: 0.10, waveInterval: 4000,
      label: "Ir",
      bgGradient: "linear-gradient(180deg,#1a0030 0%,#4c1d95 30%,#7c3aed 65%,#c084fc 100%)",
      bubbleBg: "#ede9fe", bubbleText: "#5b21b6",
      progressGrad: "linear-gradient(90deg,#c084fc,#9333ea)",
      badgeColor: "rgba(147,51,234,0.5)",
    },
    accentColor: "linear-gradient(135deg,#c084fc,#9333ea)",
  },
  33: {
    songNumber: 33,
    title: "Decir Fly",
    icon: "🗣️",
    phaseConfig: {
      words: [
        { spanish: "digo",        english: "I say"        },
        { spanish: "dices",       english: "you say"      },
        { spanish: "dice",        english: "he/she says"  },
        { spanish: "decimos",     english: "we say"       },
        { spanish: "dicen",       english: "they say"     },
        { spanish: "hola",        english: "hello"        },
        { spanish: "sí",          english: "yes"          },
        { spanish: "aquí",        english: "here"         },
        { spanish: "buenos días", english: "good morning" },
        { spanish: "verdad",      english: "truth"        },
        { spanish: "felicidad",   english: "happiness"    },
        { spanish: "explicar",    english: "to explain"   },
        { spanish: "nombre",      english: "name"         },
        { spanish: "chiste",      english: "joke"         },
        { spanish: "decir",       english: "to say"       },
      ],
      speedBase: 0.28, speedVariance: 0.10, waveInterval: 4200,
      label: "Decir",
      bgGradient: "linear-gradient(180deg,#1a0030 0%,#4c1d95 30%,#7c3aed 65%,#c084fc 100%)",
      bubbleBg: "#ede9fe", bubbleText: "#5b21b6",
      progressGrad: "linear-gradient(90deg,#c084fc,#9333ea)",
      badgeColor: "rgba(147,51,234,0.5)",
    },
    accentColor: "linear-gradient(135deg,#c084fc,#9333ea)",
  },

  // ═══════════════════════════════════════════════════════════════
  // VERB GALAXY — Quick Past World (Songs 34-37)
  // ═══════════════════════════════════════════════════════════════
  34: {
    songNumber: 34,
    title: "Pretérito Fly",
    icon: "⏪",
    phaseConfig: {
      words: [
        { spanish: "ayer",           english: "yesterday"       },
        { spanish: "anoche",         english: "last night"      },
        { spanish: "una vez",        english: "once"            },
        { spanish: "de repente",     english: "suddenly"        },
        { spanish: "hace tiempo",    english: "a while ago"     },
        { spanish: "hablé",          english: "I spoke"         },
        { spanish: "comiste",        english: "you ate"         },
        { spanish: "corrió",         english: "he ran"          },
        { spanish: "escribió",       english: "she wrote"       },
        { spanish: "bailamos",       english: "we danced"       },
        { spanish: "vivieron",       english: "they lived"      },
      ],
      speedBase: 0.28, speedVariance: 0.10, waveInterval: 4200,
      label: "Pretérito",
      bgGradient: "linear-gradient(180deg,#1a0800 0%,#7c2d12 30%,#c2410c 65%,#fb923c 100%)",
      bubbleBg: "#ffedd5", bubbleText: "#9a3412",
      progressGrad: "linear-gradient(90deg,#fb923c,#ea580c)",
      badgeColor: "rgba(194,65,12,0.5)",
    },
    accentColor: "linear-gradient(135deg,#fb923c,#ea580c)",
  },
  35: {
    songNumber: 35,
    title: "AR Pretérito Fly",
    icon: "⏪",
    phaseConfig: {
      words: [
        { spanish: "hablar",   english: "to speak"     },
        { spanish: "caminar",  english: "to walk"      },
        { spanish: "cocinar",  english: "to cook"      },
        { spanish: "mirar",    english: "to look/watch"},
        { spanish: "é",        english: "I (ending)"   },
        { spanish: "aste",     english: "you (ending)" },
        { spanish: "ó",        english: "he/she (ending)"},
        { spanish: "amos",     english: "we (ending)"  },
        { spanish: "aron",       english: "they (ending)"},
        { spanish: "hablé",      english: "I spoke"       },
        { spanish: "caminó",     english: "he/she walked" },
        { spanish: "cocinamos",  english: "we cooked"     },
        { spanish: "miraron",    english: "they watched"  },
      ],
      speedBase: 0.28, speedVariance: 0.10, waveInterval: 4200,
      label: "AR Past",
      bgGradient: "linear-gradient(180deg,#1a0800 0%,#7c2d12 30%,#c2410c 65%,#fb923c 100%)",
      bubbleBg: "#ffedd5", bubbleText: "#9a3412",
      progressGrad: "linear-gradient(90deg,#fb923c,#ea580c)",
      badgeColor: "rgba(194,65,12,0.5)",
    },
    accentColor: "linear-gradient(135deg,#fb923c,#ea580c)",
  },
  36: {
    songNumber: 36,
    title: "ER/IR Pretérito Fly",
    icon: "⏪",
    phaseConfig: {
      words: [
        { spanish: "comer",     english: "to eat"     },
        { spanish: "beber",     english: "to drink"   },
        { spanish: "escribir",  english: "to write"   },
        { spanish: "vivir",     english: "to live"    },
        { spanish: "í",         english: "I (ending)"    },
        { spanish: "iste",      english: "you (ending)"  },
        { spanish: "ió",        english: "he/she (ending)"},
        { spanish: "imos",      english: "we (ending)"   },
        { spanish: "ieron",      english: "they (ending)" },
        { spanish: "comí",       english: "I ate"         },
        { spanish: "bebiste",    english: "you drank"     },
        { spanish: "escribió",   english: "he/she wrote"  },
        { spanish: "vivimos",    english: "we lived"      },
        { spanish: "comieron",   english: "they ate"      },
      ],
      speedBase: 0.28, speedVariance: 0.10, waveInterval: 4200,
      label: "ER/IR Past",
      bgGradient: "linear-gradient(180deg,#1a0800 0%,#7c2d12 30%,#c2410c 65%,#fb923c 100%)",
      bubbleBg: "#ffedd5", bubbleText: "#9a3412",
      progressGrad: "linear-gradient(90deg,#fb923c,#ea580c)",
      badgeColor: "rgba(194,65,12,0.5)",
    },
    accentColor: "linear-gradient(135deg,#fb923c,#ea580c)",
  },
  37: {
    songNumber: 37,
    title: "Irregular Past Fly",
    icon: "⏪",
    phaseConfig: {
      words: [
        { spanish: "estar",    english: "was/were (estuv-)"  },
        { spanish: "poder",    english: "could (pud-)"       },
        { spanish: "poner",    english: "put (pus-)"         },
        { spanish: "saber",    english: "knew (sup-)"        },
        { spanish: "tener",    english: "had (tuv-)"         },
        { spanish: "venir",    english: "came (vin-)"        },
        { spanish: "querer",   english: "wanted (quis-)"     },
        { spanish: "hacer",    english: "did/made (hic-)"    },
        { spanish: "decir",    english: "said (dij-)"        },
        { spanish: "traer",    english: "brought (traj-)"    },
        { spanish: "conducir", english: "drove (conduj-)"    },
      ],
      speedBase: 0.30, speedVariance: 0.12, waveInterval: 4000,
      label: "Irregular Past",
      bgGradient: "linear-gradient(180deg,#1a0800 0%,#7c2d12 30%,#c2410c 65%,#fb923c 100%)",
      bubbleBg: "#ffedd5", bubbleText: "#9a3412",
      progressGrad: "linear-gradient(90deg,#fb923c,#ea580c)",
      badgeColor: "rgba(194,65,12,0.5)",
    },
    accentColor: "linear-gradient(135deg,#fb923c,#ea580c)",
  },

  // ═══════════════════════════════════════════════════════════════
  // VERB GALAXY — Long Past World (Songs 38-40)
  // ═══════════════════════════════════════════════════════════════
  38: {
    songNumber: 38,
    title: "Imperfecto Fly",
    icon: "🔄",
    phaseConfig: {
      words: [
        { spanish: "era",     english: "was/were (used to be)" },
        { spanish: "iba",     english: "used to go"    },
        { spanish: "veía",    english: "used to see"   },
        { spanish: "aba",     english: "-AR I/he (ending)"   },
        { spanish: "abas",    english: "-AR you (ending)"    },
        { spanish: "ábamos",  english: "-AR we (ending)"     },
        { spanish: "aban",    english: "-AR they (ending)"   },
        { spanish: "ía",      english: "-ER/-IR I/he (ending)" },
        { spanish: "ías",     english: "-ER/-IR you (ending)"  },
        { spanish: "íamos",   english: "-ER/-IR we (ending)"   },
        { spanish: "ían",     english: "-ER/-IR they (ending)" },
      ],
      speedBase: 0.28, speedVariance: 0.10, waveInterval: 4200,
      label: "Imperfecto",
      bgGradient: "linear-gradient(180deg,#1a1000 0%,#713f12 30%,#a16207 65%,#fde047 100%)",
      bubbleBg: "#fef9c3", bubbleText: "#854d0e",
      progressGrad: "linear-gradient(90deg,#fde047,#ca8a04)",
      badgeColor: "rgba(161,98,7,0.5)",
    },
    accentColor: "linear-gradient(135deg,#fde047,#ca8a04)",
  },
  39: {
    songNumber: 39,
    title: "Imperfecto Irreg. Fly",
    icon: "🔄",
    phaseConfig: {
      words: [
        { spanish: "era",    english: "I/he was (ser)"     },
        { spanish: "eras",   english: "you were (ser)"     },
        { spanish: "éramos", english: "we were (ser)"      },
        { spanish: "eran",   english: "they were (ser)"    },
        { spanish: "iba",    english: "I/he went (ir)"     },
        { spanish: "ibas",   english: "you went (ir)"      },
        { spanish: "íbamos", english: "we went (ir)"       },
        { spanish: "iban",   english: "they went (ir)"     },
        { spanish: "veía",   english: "I/he saw (ver)"     },
        { spanish: "veías",  english: "you saw (ver)"      },
        { spanish: "veíamos",english: "we saw (ver)"       },
        { spanish: "veían",  english: "they saw (ver)"     },
      ],
      speedBase: 0.28, speedVariance: 0.10, waveInterval: 4200,
      label: "Irregulars",
      bgGradient: "linear-gradient(180deg,#1a1000 0%,#713f12 30%,#a16207 65%,#fde047 100%)",
      bubbleBg: "#fef9c3", bubbleText: "#854d0e",
      progressGrad: "linear-gradient(90deg,#fde047,#ca8a04)",
      badgeColor: "rgba(161,98,7,0.5)",
    },
    accentColor: "linear-gradient(135deg,#fde047,#ca8a04)",
  },
  40: {
    songNumber: 40,
    title: "Imperfecto vs Pretérito Fly",
    icon: "🔄",
    phaseConfig: {
      words: [
        { spanish: "era",       english: "was (imperfect)"     },
        { spanish: "fue",       english: "was (preterite)"     },
        { spanish: "iba",       english: "went (imperfect)"    },
        { spanish: "fui",       english: "went (preterite)"    },
        { spanish: "hacía",     english: "did (imperfect)"     },
        { spanish: "hizo",      english: "did (preterite)"     },
        { spanish: "tenía",     english: "had (imperfect)"     },
        { spanish: "tuvo",      english: "had (preterite)"     },
        { spanish: "siempre",   english: "always"              },
        { spanish: "de repente", english: "suddenly"            },
      ],
      speedBase: 0.30, speedVariance: 0.10, waveInterval: 4000,
      label: "Imp. vs Pret.",
      bgGradient: "linear-gradient(180deg,#1a1000 0%,#713f12 30%,#a16207 65%,#fde047 100%)",
      bubbleBg: "#fef9c3", bubbleText: "#854d0e",
      progressGrad: "linear-gradient(90deg,#fde047,#ca8a04)",
      badgeColor: "rgba(161,98,7,0.5)",
    },
    accentColor: "linear-gradient(135deg,#fde047,#ca8a04)",
  },

  // ═══════════════════════════════════════════════════════════════
  // VERB GALAXY — Future World (Songs 41-42)
  // ═══════════════════════════════════════════════════════════════
  41: {
    songNumber: 41,
    title: "Futuro Fly",
    icon: "⏩",
    phaseConfig: {
      words: [
        { spanish: "cantaré",  english: "I will sing"   },
        { spanish: "comeré",   english: "I will eat"    },
        { spanish: "viviré",   english: "I will live"   },
        { spanish: "é",        english: "I (ending)"    },
        { spanish: "ás",       english: "you (ending)"  },
        { spanish: "á",        english: "he/she (ending)"},
        { spanish: "emos",     english: "we (ending)"   },
        { spanish: "án",         english: "they (ending)" },
        { spanish: "futuro",     english: "future"        },
        { spanish: "hablaré",    english: "I will speak"  },
        { spanish: "escribiré",  english: "I will write"  },
      ],
      speedBase: 0.28, speedVariance: 0.10, waveInterval: 4200,
      label: "Futuro",
      bgGradient: "linear-gradient(180deg,#001a30 0%,#0c4a6e 30%,#0369a1 65%,#38bdf8 100%)",
      bubbleBg: "#e0f2fe", bubbleText: "#075985",
      progressGrad: "linear-gradient(90deg,#38bdf8,#0369a1)",
      badgeColor: "rgba(3,105,161,0.5)",
    },
    accentColor: "linear-gradient(135deg,#38bdf8,#0369a1)",
  },
  42: {
    songNumber: 42,
    title: "Future Irregulars Fly",
    icon: "⏩",
    phaseConfig: {
      words: [
        { spanish: "tendré",  english: "I will have"        },
        { spanish: "diré",    english: "I will say"         },
        { spanish: "haré",    english: "I will do"          },
        { spanish: "saldré",  english: "I will leave"       },
        { spanish: "vendré",  english: "I will come"        },
        { spanish: "querré",  english: "I will want"        },
        { spanish: "sabré",   english: "I will know"        },
        { spanish: "pondré",  english: "I will put"         },
        { spanish: "podré",   english: "I will be able"     },
        { spanish: "habré",   english: "I will have (aux.)" },
        { spanish: "cabré",   english: "I will fit"         },
        { spanish: "valdré",  english: "I will be worth"    },
      ],
      speedBase: 0.30, speedVariance: 0.12, waveInterval: 3800,
      label: "Irregulars",
      bgGradient: "linear-gradient(180deg,#001a30 0%,#0c4a6e 30%,#0369a1 65%,#38bdf8 100%)",
      bubbleBg: "#e0f2fe", bubbleText: "#075985",
      progressGrad: "linear-gradient(90deg,#38bdf8,#0369a1)",
      badgeColor: "rgba(3,105,161,0.5)",
    },
    accentColor: "linear-gradient(135deg,#38bdf8,#0369a1)",
  },

  // ═══════════════════════════════════════════════════════════════
  // VERB GALAXY — Conditional World (Songs 43-44)
  // ═══════════════════════════════════════════════════════════════
  43: {
    songNumber: 43,
    title: "Condicional Fly",
    icon: "🤔",
    phaseConfig: {
      words: [
        { spanish: "cantaría",  english: "I would sing"  },
        { spanish: "comerías",  english: "you would eat" },
        { spanish: "viviría",   english: "he would live" },
        { spanish: "ía",        english: "I/he (ending)" },
        { spanish: "ías",       english: "you (ending)"  },
        { spanish: "íamos",     english: "we (ending)"   },
        { spanish: "ían",          english: "they (ending)"  },
        { spanish: "condicional",  english: "conditional"    },
        { spanish: "hablaría",     english: "I would speak"  },
        { spanish: "escribiría",   english: "I would write"  },
      ],
      speedBase: 0.28, speedVariance: 0.10, waveInterval: 4200,
      label: "Condicional",
      bgGradient: "linear-gradient(180deg,#001a25 0%,#155e75 30%,#0e7490 65%,#67e8f9 100%)",
      bubbleBg: "#cffafe", bubbleText: "#155e75",
      progressGrad: "linear-gradient(90deg,#67e8f9,#0e7490)",
      badgeColor: "rgba(14,116,144,0.5)",
    },
    accentColor: "linear-gradient(135deg,#67e8f9,#0e7490)",
  },
  44: {
    songNumber: 44,
    title: "Conditional Irreg. Fly",
    icon: "🤔",
    phaseConfig: {
      words: [
        { spanish: "tendría",  english: "would have"         },
        { spanish: "diría",    english: "would say"          },
        { spanish: "haría",    english: "would do"           },
        { spanish: "saldría",  english: "would leave"        },
        { spanish: "vendría",  english: "would come"         },
        { spanish: "querría",  english: "would want"         },
        { spanish: "sabría",   english: "would know"         },
        { spanish: "pondría",  english: "would put"          },
        { spanish: "podría",   english: "would be able"      },
        { spanish: "habría",   english: "would have (aux.)"  },
        { spanish: "valdría",  english: "would be worth"     },
      ],
      speedBase: 0.30, speedVariance: 0.12, waveInterval: 3800,
      label: "Irregulars",
      bgGradient: "linear-gradient(180deg,#001a25 0%,#155e75 30%,#0e7490 65%,#67e8f9 100%)",
      bubbleBg: "#cffafe", bubbleText: "#155e75",
      progressGrad: "linear-gradient(90deg,#67e8f9,#0e7490)",
      badgeColor: "rgba(14,116,144,0.5)",
    },
    accentColor: "linear-gradient(135deg,#67e8f9,#0e7490)",
  },

  // ═══════════════════════════════════════════════════════════════
  // VERB GALAXY — Pronoun World (Songs 45-46)
  // ═══════════════════════════════════════════════════════════════
  45: {
    songNumber: 45,
    title: "Reflexive Verbs Fly",
    icon: "👥",
    phaseConfig: {
      words: [
        { spanish: "me",          english: "myself"       },
        { spanish: "te",          english: "yourself"     },
        { spanish: "se",          english: "himself/herself"},
        { spanish: "nos",         english: "ourselves"    },
        { spanish: "despertarse", english: "to wake up"   },
        { spanish: "irse",        english: "to leave"     },
        { spanish: "prepararse",  english: "to prepare"   },
        { spanish: "cepillarse",  english: "to brush"     },
        { spanish: "lavarse",     english: "to wash"      },
        { spanish: "peinarse",    english: "to comb"      },
        { spanish: "dormirse",    english: "to go to sleep"},
      ],
      speedBase: 0.28, speedVariance: 0.10, waveInterval: 4200,
      label: "Reflexive",
      bgGradient: "linear-gradient(180deg,#001a15 0%,#064e3b 30%,#047857 65%,#6ee7b7 100%)",
      bubbleBg: "#d1fae5", bubbleText: "#065f46",
      progressGrad: "linear-gradient(90deg,#6ee7b7,#047857)",
      badgeColor: "rgba(4,120,87,0.5)",
    },
    accentColor: "linear-gradient(135deg,#6ee7b7,#047857)",
  },
  46: {
    songNumber: 46,
    title: "Object Pronouns Fly",
    icon: "👥",
    phaseConfig: {
      words: [
        { spanish: "me lo",  english: "it to me"       },
        { spanish: "te la",  english: "it (f) to you"  },
        { spanish: "nos los",english: "them (m) to us" },
        { spanish: "se lo",  english: "it to him/her"  },
        { spanish: "dar",    english: "to give"        },
        { spanish: "mandar", english: "to send"        },
        { spanish: "explicar",english: "to explain"    },
        { spanish: "mostrar", english: "to show"       },
        { spanish: "traer",  english: "to bring"       },
      ],
      speedBase: 0.28, speedVariance: 0.10, waveInterval: 4200,
      label: "Object Pronouns",
      bgGradient: "linear-gradient(180deg,#001a15 0%,#064e3b 30%,#047857 65%,#6ee7b7 100%)",
      bubbleBg: "#d1fae5", bubbleText: "#065f46",
      progressGrad: "linear-gradient(90deg,#6ee7b7,#047857)",
      badgeColor: "rgba(4,120,87,0.5)",
    },
    accentColor: "linear-gradient(135deg,#6ee7b7,#047857)",
  },

  // ═══════════════════════════════════════════════════════════════
  // VERB GALAXY — Advanced World (Songs 47-50)
  // ═══════════════════════════════════════════════════════════════
  47: {
    songNumber: 47,
    title: "Commands Fly",
    icon: "🎓",
    phaseConfig: {
      words: [
        { spanish: "ven",        english: "come"          },
        { spanish: "habla",      english: "speak"         },
        { spanish: "escribe",    english: "write"         },
        { spanish: "come",       english: "eat"           },
        { spanish: "corre",      english: "run"           },
        { spanish: "haz",        english: "do/make"       },
        { spanish: "mira",       english: "look"          },
        { spanish: "no corras",  english: "don't run"     },
        { spanish: "no hables",  english: "don't speak"   },
        { spanish: "no toques",  english: "don't touch"   },
        { spanish: "no mientas", english: "don't lie"     },
        { spanish: "no fumes",   english: "don't smoke"   },
        { spanish: "no olvides", english: "don't forget"  },
      ],
      speedBase: 0.30, speedVariance: 0.12, waveInterval: 3800,
      label: "Mandatos",
      bgGradient: "linear-gradient(180deg,#0a0028 0%,#312e81 30%,#4338ca 65%,#818cf8 100%)",
      bubbleBg: "#e0e7ff", bubbleText: "#3730a3",
      progressGrad: "linear-gradient(90deg,#818cf8,#4338ca)",
      badgeColor: "rgba(67,56,202,0.5)",
    },
    accentColor: "linear-gradient(135deg,#818cf8,#4338ca)",
  },
  48: {
    songNumber: 48,
    title: "Por vs Para Fly",
    icon: "🎓",
    phaseConfig: {
      words: [
        { spanish: "para",        english: "for (recipient)"   },
        { spanish: "por",         english: "because of"        },
        { spanish: "gracias por", english: "thanks for"        },
        { spanish: "gracias",    english: "thank you"        },
      ],
      speedBase: 0.26, speedVariance: 0.08, waveInterval: 4500,
      label: "Por vs Para",
      bgGradient: "linear-gradient(180deg,#0a0028 0%,#312e81 30%,#4338ca 65%,#818cf8 100%)",
      bubbleBg: "#e0e7ff", bubbleText: "#3730a3",
      progressGrad: "linear-gradient(90deg,#818cf8,#4338ca)",
      badgeColor: "rgba(67,56,202,0.5)",
    },
    accentColor: "linear-gradient(135deg,#818cf8,#4338ca)",
  },
  49: {
    songNumber: 49,
    title: "Subjunctive Fly",
    icon: "🎓",
    phaseConfig: {
      words: [
        { spanish: "quiero que",         english: "I want that"           },
        { spanish: "espero que",         english: "I hope that"           },
        { spanish: "es importante que",  english: "it's important that"   },
        { spanish: "ojalá que",          english: "I wish"                },
        { spanish: "temo que",           english: "I fear that"           },
        { spanish: "me alegra que",      english: "I'm happy that"        },
        { spanish: "no creo que",        english: "I don't believe that"  },
      ],
      speedBase: 0.26, speedVariance: 0.08, waveInterval: 4500,
      label: "Subjuntivo",
      bgGradient: "linear-gradient(180deg,#0a0028 0%,#312e81 30%,#4338ca 65%,#818cf8 100%)",
      bubbleBg: "#e0e7ff", bubbleText: "#3730a3",
      progressGrad: "linear-gradient(90deg,#818cf8,#4338ca)",
      badgeColor: "rgba(67,56,202,0.5)",
    },
    accentColor: "linear-gradient(135deg,#818cf8,#4338ca)",
  },
  50: {
    songNumber: 50,
    title: "Spanish Slang Fly",
    icon: "🎓",
    phaseConfig: {
      words: [
        { spanish: "¿qué onda?",   english: "what's up?"    },
        { spanish: "qué padre",    english: "cool"          },
        { spanish: "órale",        english: "wow / let's go"},
        { spanish: "no manches",   english: "no way"        },
        { spanish: "guay",         english: "cool (Spain)"  },
        { spanish: "chévere",      english: "cool (Venez.)" },
        { spanish: "bacán",        english: "cool (Chile)"  },
        { spanish: "vale",         english: "okay (Spain)"  },
        { spanish: "aguas",        english: "watch out"     },
        { spanish: "ni modo",      english: "no problem"    },
        { spanish: "pan comido",   english: "it's easy"     },
        { spanish: "me cae gordo", english: "it annoys me"  },
        { spanish: "onda",         english: "vibe"          },
        { spanish: "padre",        english: "cool"          },
      ],
      speedBase: 0.30, speedVariance: 0.12, waveInterval: 3800,
      label: "Slang",
      bgGradient: "linear-gradient(180deg,#0a0028 0%,#312e81 30%,#4338ca 65%,#818cf8 100%)",
      bubbleBg: "#e0e7ff", bubbleText: "#3730a3",
      progressGrad: "linear-gradient(90deg,#818cf8,#4338ca)",
      badgeColor: "rgba(67,56,202,0.5)",
    },
    accentColor: "linear-gradient(135deg,#818cf8,#4338ca)",
  },
}
